<a href="https://colab.research.google.com/github/avishkajindal05/DAY-25-AM/blob/main/part_A_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PART - A

In [37]:
import requests
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
def download_data():
  url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
  filename = 'iris.csv'
  current_directory = os.getcwd()
  file_path = os.path.join(current_directory,filename)
  if not os.path.exists(file_path):
    print("Downloading",filename,"to",current_directory,"...")
    response = requests.get(url=url)
    with open(file_path, "wb") as f:
      f.write(response.content)

    print("Download compelete")
  else:
    print(f"{filename} already exists in {current_directory}")

In [39]:
download_data()

iris.csv already exists in /content


In [40]:
import os

filename = "iris.csv"
filepath = os.path.join(os.getcwd(),filename)

In [41]:
df = pd.read_csv("iris.csv")

In [42]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [43]:
df.tail()

,sepal_length,sepal_width,petal_length,petal_width,species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica


In [44]:
df.shape

(150, 5)

In [45]:
df.head(0)

,sepal_length,sepal_width,petal_length,petal_width,species


In [46]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [47]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [49]:
print(df.isnull().sum())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [50]:
mean_splen = df["sepal_length"].mean()
print(mean_splen)

5.843333333333334


In [51]:
mean_spwd = df["sepal_width"].mean()

In [52]:
df["species"].is_unique

False

In [53]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [54]:
df["sepal_length"].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [55]:
df.groupby("species")["sepal_length"].unique()

,sepal_length
species,
setosa,"[5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.4, 4.8, 4.3, ..."
versicolor,"[7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, ..."
virginica,"[6.3, 5.8, 7.1, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, ..."


In [56]:
df["sepal_width"].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [57]:
df.groupby("species")["sepal_width"].unique()

,sepal_width
species,
setosa,"[3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, ..."
versicolor,"[3.2, 3.1, 2.3, 2.8, 3.3, 2.4, 2.9, 2.7, 2.0, ..."
virginica,"[3.3, 2.7, 3.0, 2.9, 2.5, 3.6, 3.2, 2.8, 3.8, ..."


In [58]:
df["petal_length"].unique()

array([1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1. , 1.9, 4.7, 4.5, 4.9, 4. ,
       4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5. , 3.8, 3.7,
       5.1, 3. , 6. , 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7, 6.9,
       5.7, 6.4, 5.4, 5.2])

In [59]:
df.groupby("species")["petal_length"].unique()

,petal_length
species,
setosa,"[1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9]"
versicolor,"[4.7, 4.5, 4.9, 4.0, 4.6, 3.3, 3.9, 3.5, 4.2, ..."
virginica,"[6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 6.1, ..."


In [60]:
df["petal_width"].unique()

array([0.2, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1, 1.8,
       1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

In [61]:
df.groupby("species")["petal_width"].unique()

,petal_width
species,
setosa,"[0.2, 0.4, 0.3, 0.1, 0.5, 0.6]"
versicolor,"[1.4, 1.5, 1.3, 1.6, 1.0, 1.1, 1.8, 1.2, 1.7]"
virginica,"[2.5, 1.9, 2.1, 1.8, 2.2, 1.7, 2.0, 2.4, 2.3, ..."


In [62]:
df["petal_length"].value_counts()

,count
petal_length,
1.5,14
1.4,12
4.5,8
5.1,8
1.3,7
1.6,7
5.6,6
4.9,5
4.0,5


In [63]:
df["petal_length"].value_counts()

,count
petal_length,
1.5,14
1.4,12
4.5,8
5.1,8
1.3,7
1.6,7
5.6,6
4.9,5
4.0,5


In [64]:
df["sepal_length"].value_counts()

,count
sepal_length,
5.0,10
6.3,9
5.1,9
6.7,8
5.7,8
6.4,7
5.5,7
5.8,7
4.9,6


In [65]:
df["sepal_width"].value_counts()

,count
sepal_width,
3.0,26
2.8,14
3.2,13
3.4,12
3.1,12
2.9,10
2.7,9
2.5,8
3.3,6


In [66]:
df["species"].value_counts()

,count
species,
setosa,50
versicolor,50
virginica,50


PART - B

In [67]:
df.groupby("species")["petal_length"] == 1.4

False

In [68]:
data = df.loc[df["petal_length"] <= 5]
print(data)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
123           6.3          2.7           4.9          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
146           6.3          2.5           5.0          1.9  virginica

[108 rows x 5 columns]


In [69]:
data.groupby("species").count()


,sepal_length,sepal_width,petal_length,petal_width
species,,,,
setosa,50,50,50,50
versicolor,49,49,49,49
virginica,9,9,9,9


In [70]:
data.groupby("sepal_length").count()


,sepal_width,petal_length,petal_width,species
sepal_length,,,,
4.3,1,1,1,1
4.4,3,3,3,3
4.5,1,1,1,1
4.6,4,4,4,4
4.7,2,2,2,2
4.8,5,5,5,5
4.9,6,6,6,6
5.0,10,10,10,10
5.1,9,9,9,9


In [71]:
data.groupby("species").mean()


,sepal_length,sepal_width,petal_length,petal_width
species,,,,
setosa,5.006000,3.418000,1.464000,0.244000
versicolor,5.934694,2.771429,4.242857,1.320408
virginica,5.900000,2.666667,4.866667,1.811111


In [72]:
df[df["sepal_width"] > 3]

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
...,...,...,...,...,...
140,6.7,3.1,5.6,2.4,virginica
141,6.9,3.1,5.1,2.3,virginica
143,6.8,3.2,5.9,2.3,virginica
144,6.7,3.3,5.7,2.5,virginica


In [73]:
df["sepal"] = df["sepal_length"] + df["sepal_width"]

In [74]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal
0,5.1,3.5,1.4,0.2,setosa,8.6
1,4.9,3.0,1.4,0.2,setosa,7.9
2,4.7,3.2,1.3,0.2,setosa,7.9
3,4.6,3.1,1.5,0.2,setosa,7.7
4,5.0,3.6,1.4,0.2,setosa,8.6


In [87]:
data_sort = df.sort_values(by = "sepal", axis = 0, ascending = False, inplace = False, kind = "heapsort", ignore_index = False )
data_sort

,sepal_length,sepal_width,petal_length,petal_width,species,sepal
131,7.9,3.8,6.4,2.0,virginica,11.7
117,7.7,3.8,6.7,2.2,virginica,11.5
109,7.2,3.6,6.1,2.5,virginica,10.8
135,7.7,3.0,6.1,2.3,virginica,10.7
105,7.6,3.0,6.6,2.1,virginica,10.6
...,...,...,...,...,...,...
57,4.9,2.4,3.3,1.0,versicolor,7.3
93,5.0,2.3,3.3,1.0,versicolor,7.3
13,4.3,3.0,1.1,0.1,setosa,7.3
60,5.0,2.0,3.5,1.0,versicolor,7.0


In [88]:
print(df["sepal"] > 7)

0      True
1      True
2      True
3      True
4      True
       ... 
145    True
146    True
147    True
148    True
149    True
Name: sepal, Length: 150, dtype: bool


In [91]:
data_sort.head(15)

,sepal_length,sepal_width,petal_length,petal_width,species,sepal
131,7.9,3.8,6.4,2.0,virginica,11.7
117,7.7,3.8,6.7,2.2,virginica,11.5
109,7.2,3.6,6.1,2.5,virginica,10.8
135,7.7,3.0,6.1,2.3,virginica,10.7
105,7.6,3.0,6.6,2.1,virginica,10.6
122,7.7,2.8,6.7,2.0,virginica,10.5
125,7.2,3.2,6.0,1.8,virginica,10.4
118,7.7,2.6,6.9,2.3,virginica,10.3
130,7.4,2.8,6.1,1.9,virginica,10.2
129,7.2,3.0,5.8,1.6,virginica,10.2


In [93]:
df.groupby("species")["sepal_width"].mean()

,sepal_width
species,
setosa,3.418
versicolor,2.770
virginica,2.974


In [95]:
df.groupby("sepal_width")["sepal_length"].mean()

,sepal_length
sepal_width,
2.0,5.000000
2.2,6.066667
2.3,5.325000
2.4,5.300000
2.5,5.762500
2.6,6.160000
2.7,5.855556
2.8,6.335714
2.9,6.060000
